# Site settings
title: Aditya Karanam
email: karanam@nus.edu.sg
description: > # this means to ignore newlines until "baseurl:"
  I'm an Assistant Professor in the Department of Information Systems and Analytics at the School of Computing in the National University of Singapore. My research interests are in the
  areas of Networked Economy and Economics of Information Systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://askaranam.github.io" # the base hostname & protocol for your site
twitter_username: aditya_karanam
github_username:  askaranam


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Doctoral Candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: ""
google_site_verification: ""
bing_webmastertools_id: ""

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
