# Site settings
title: Aditya Karanam
email: aditya.karanam@utdallas.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm an Assistant Professor in the Naveen Jindal School of Management, University of Texas at Dallas. My research interests are in the
  areas of Digital Platforms, Networked Economy and Economics of AI.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://askaranam.github.io" # the base hostname & protocol for your site
twitter_username: aditya_karanam
github_username:  askaranam


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: ""
google_site_verification: ""
bing_webmastertools_id: ""

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
